### PR TITLE
add a button to mark all notifications as read

### PR DESCRIPTION
**Pull request by Bad-Y**
This feature introduce a button that will mark all notifications as read

### CODE REVIEW

**Comment by sue445** [comment]
@Bad-Y Thank you.  think this feature is duplicate to "Clear cache"

`markAllAsRead ` (clear only `notifiedHistories` cache) is contained `clearConfigCache` (clear all cache)

* https://github.com/sue445/chrome-gitlab-notifier/blob/2.1.2/src/popup.js#L52-L60
* https://github.com/sue445/chrome-gitlab-notifier/blob/2.1.2/src/popup_init.js#L26-L28
* https://github.com/sue445/chrome-gitlab-notifier/blob/2.1.2/src/config.js#L130-L136

What are difference?

**Comment by Bad-Y** [comment]
@sue445 Thank _you_ for this awesome extension !

It is indeed very similar to "Clear cache" the only difference lie in the cache :

When you add a new repo to be watched you get a lot of notifications and you must remove them one by one, you can click on the "Clear cache" button and all the notifications will be gone **but** they will pop again in the next polling.

This feature simply mark them as read by remove them from the history **without** removing them from cache so they won't pop again.

Thanks again.

**Comment by sue445** [comment]
@Bad-Y 

> This feature simply mark them as read by remove them from the history without removing them from cache so they won't pop again.

I see. This is good feature!

**Comment by sue445** [comment]
Released v2.2.0

**Pull request merged**
