### PR TITLE
Add margin

### PR DESCRIPTION
**Pull request by pengbins**
* add icons for  headers in option page
   * bell icon for Notification Setting
   * envelop icon for Repository Events
* add margin between icon and text
* add margin between buttons

### CODE REVIEW

**Comment by sue445** [comment]
It is difficult to understand how the appearance has changed only with the difference and explanation of css.

Please attach screenshots before and after change.

e.g) https://github.com/sue445/my-ci-badges/pull/4

**Comment by pengbins** [comment]
For popup page

* before
image
* after
image

**Comment by pengbins** [comment]
For option page

|  before | after |
| -------| ----- |
|  ![image][1] | ![image][2] |

[1]:https://user-images.githubusercontent.com/1439218/33251638-382e3c3c-d373-11e7-8600-b979d1e2d39a.png
[2]:https://user-images.githubusercontent.com/1439218/33251645-3e136262-d373-11e7-8a01-078291669910.png

**Comment by sue445** [comment]
LGTM

**Pull request merged**
